---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: foo-controller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: foo-controller-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: foo-controller
  name: foo-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-controller
  template:
    metadata:
      labels:
        app: foo-controller
    spec:
      containers:
      - image: gcr.io/nmiu-play/sample-controller:latest
        imagePullPolicy: Always
        name: foo-controller
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
      serviceAccountName: foo-controller-sa
