apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - projectName
          - clusterName
          - location
          - sidecarTag
          - sidecarArgs
          properties:
            projectName:
              type: string
            clusterName:
              type: string
            location:
              type: string
            sidecarTag:
              type: string
            sidecarArgs:
              type: array
              items:
                type: string
